name: mkblue-laptop
description: 

base-image: ghcr.io/secureblue/silverblue-main-userns-hardened
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/mkkvcs/fedora/refs/heads/main/protonvpn-stable.repo
    install:
      - zsh
      - neovim
      - easyeffects
      - fastfetch
      - solaar
      - proton-vpn-gnome-desktop
      
  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - io.github.shiftey.Desktop
        - org.qbittorrent.qBittorrent
        - com.jetbrains.Rider
        - com.stremio.Stremio
        - com.github.tchx84.Flatseal
        - org.gnome.Extensions
        - org.gnome.eog
        - org.gnome.Evince
        
  - type: script
    scripts:
      - chromium-laptop.sh
      
  - type: signing
