name: mkblue-laptop
description: ha

base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - type: rpm-ostree
    install:
      - zsh
      - neovim
      - easyeffects
      - solaar
      
  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - io.github.shiftey.Desktop
        - org.qbittorrent.qBittorrent
        - com.jetbrains.Rider
        - com.protonvpn.www
        - org.gnome.Extensions
        - org.gnome.Papers
        - org.gnome.TextEditor
      
  - type: script
    scripts:
      - chromium-laptop.sh
      
  - type: signing
